import 'package:get/get.dart';
import 'package:voithy/ui/localization/app_strings.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          AppStrings.greeting: 'اهلا و سهلا',
          AppStrings.trackMedication: ' تتبع الأدوية\n والأعراض الخاصة بك',
          AppStrings.helloAndWelcomeHere: 'اهلا ومرحبا بكم هنا!',
          AppStrings.letsStart: 'ابدأ',
          AppStrings.chooseYourLanguage: 'اختر لغتك',
          AppStrings.getAnOverView:
              'احصل على نظرة عامة على تقدم علاجك وتحفز للالتزام',
          AppStrings.trackYourMedicationAndSymptoms:
              'تتبع الأدوية والأعراض الخاصة بك',
          AppStrings.letUsHelpYou:
              'دعنا نساعدك في إدارة جداول الأدوية المعقدة ومستويات المخزون',
          AppStrings.alreadyAMember: 'عضوا فعلا؟',
          AppStrings.signIn: 'تسجيل الدخول',
          AppStrings.neverMissADoseAgain: 'لا تفوت جرعة مرة أخرى',
          AppStrings.getAnOverviewOfYourTreatment:
              'احصل على نظرة عامة على تقدم علاجك وتحفيزك للالتزام وتحقيق المزيد',
          AppStrings.inviteAndManageYourCareCircle:
              'قم بدعوة وإدارة دائرة الرعاية الخاصة بك',
          AppStrings.inviteDependentsAndCaregivers:
              'ادعُ المعالين ومقدمي الرعاية لدعم بعضهم البعض في خطة العلاج الخاصة بك',
          AppStrings.arabic: "عربي",
          AppStrings.english: "English",
          AppStrings.email: "البريد الالكتروني",
          AppStrings.signUpHeader: "قم بإنشاء حساب",
          AppStrings.mobileNumber: " رقم الهاتف المحمول",
          AppStrings.password: "كلمه المرور",
          AppStrings.confirmPassword: " تأكيد كلمة المرور",
          AppStrings.signUp: "اشتراك",
          AppStrings.createAccount: "قم بإنشاء حساب",
          AppStrings.termsConditions: "الأحكام والشروط",
          AppStrings.verifyAccountH: "تحقق من حساب فويثي",
          AppStrings.verifyAccountBody:
              "ستتلقى رمزًا مكونًا من 4 أرقام للتحقق من حساب فويثي عبر البريد الإلكتروني",
          AppStrings.resendCode: "إعادة إرسال الرمز ",
          AppStrings.verifyCreateAccount: "تحقق وأنشئ حسابًا",
          AppStrings.didnotReceiveCode: "لم تتلق رمز؟",
          AppStrings.requestAgain: " اطلب مرة أخرى",
          AppStrings.pleaseEnterFirstName: "يرجى ادخال الاسم الاول",
          AppStrings.pleaseEnterLastName: "الرجاء إدخال اسمك الأخير",
          AppStrings.pleaseEnterPassword: "من فضلك أدخل رقمك السري",
          AppStrings.pleaseEnterYourEmailAddress:
              ' الرجاء إدخال عنوان البريد الإلكتروني الخاص بك',
          AppStrings.pleaseEnterYourPassword: 'من فضلك أدخل رقمك السري',
          AppStrings.dontHaveAccount: 'لا يوجد لديك حساب؟ ',
          AppStrings.forgotYourPassword: 'نسيت رقمك السري؟',
          AppStrings.changePassword: 'غير كلمه السر',
          AppStrings.newPassword: 'كلمه مرور جديدة',
          AppStrings.confirmNewPassword: ' تأكيد كلمة المرور',
          AppStrings.firstName: "الاسم الاول",
          AppStrings.lastName: "الاسم الاخير",
          AppStrings.connectWithFacebook: 'تواصل مع الفيسبوك',
          AppStrings.connectWithGoogle: 'تواصل مع جوجل',
          AppStrings.enterYourEmailAddress:
              'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة مرورك.',
          AppStrings.resetPassword: 'إعادة تعيين كلمة المرور',
          AppStrings.pleaseFillTheFieldsCorrectly: 'يرجى ملء الحقول المطلوبة بشكل صحيح',
          AppStrings.required: 'مطلوب',
          AppStrings.orContinueWith: 'أو تواصل مع',
          AppStrings.enterYourEmailCorrectly: 'أدخل بريدك الإلكتروني بشكل صحيح',

          AppStrings.seeLess: "اعرض اقل",
          AppStrings.seeMore: "اعرض المزيد",
          AppStrings.getAnOverviewOfYourTreatmentProgress:
              "احصل على نظرة عامة على تقدم علاجك وتحفز للالتزام",
          AppStrings.helloAndWelcomeToVoithy: " مرحبا واهلا بك في فويثي!",
          AppStrings.enterMobileNumber: "أدخل رقم الهاتف المحمول",
          AppStrings.enterYourEmail: "أدخل بريدك الإلكتروني",
          AppStrings.enterYourPassword: "ادخل رقمك السري",
          AppStrings.number: " رقم",
          AppStrings.nickname: " كنية",
          AppStrings.myWifeHusbandEtc: " زوجتي ، زوجي ... إلخ.",
          AppStrings.createAVoithyAccount: "قم بإنشاء حساب",
          AppStrings.iAgreeWithThe: "أتفق مع ",
          AppStrings.country: " الدولة",
          AppStrings.enterYourEmailAddressAndWellSendYou:
              "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة مرورك.",
          AppStrings.youllReceiveA4DigitCodeToVerifyVoithysAccountViaEmail:
              "ستتلقى رمزًا مكونًا من 4 أرقام للتحقق من حساب فويثي عبر البريد الإلكتروني",
          AppStrings.createAVoithyAccountForADependent:
              "قم بإنشاء حساب Voithy خاص بتابع",
          AppStrings.toJoinVoithyToGetStartedJustCreateA:
              "للانضمام إلى Voithy للبدء ، ما عليك سوى إنشاء",
          AppStrings.knowMore: "تعرف أكثر",
          AppStrings.below: "اسفل.",
          AppStrings.profile: "الملف الشخصي",
          AppStrings.fullName: "الاسم الكامل",
          AppStrings.phone: "هاتف",
          AppStrings.signUpAsdependent: "قم بالتسجيل كمعال",
          AppStrings.welcomeToVoithy: "مرحبًا بك في فويثي",
          AppStrings.yourAccountHasBeenCreatedSuccessfully:
              "تم إنشاء حسابك بنجاح",
          AppStrings.Cares: "يهتم",
          AppStrings.enterFirstName: "أدخل الاسم الأول",
          AppStrings.enterLastName: "أدخل الاسم الأخير",
          AppStrings.enterNickname: "أدخل كنية",
          AppStrings.enterEmail: "أدخل البريد الإلكتروني",
          AppStrings.minimum7Number: "الحد الأدنى 7 عدد",
          AppStrings.maximum13Number: "الحد الأقصى 13 رقمًا",
          AppStrings.enterPassword: "أدخل كلمة السر",
          AppStrings.enterOnlyNumbers: "أدخل فقط أرقام",
          AppStrings.enterOnlyTextInFirstName: "أدخل النص في الاسم الأول فقط",
          AppStrings.enterOnlyTextInLastName: "أدخل النص فقط في الاسم الأخير",
          AppStrings.enterOnlyTextInNickname: "أدخل النص فقط في اللقب",
          AppStrings.charactersAllowedInFirstName30:
              "30 حرفًا مسموحًا بها في الاسم الأول",
          AppStrings.charactersAllowedInLastName30:
              "30 حرفًا مسموحًا بها في الاسم الأخير",
          AppStrings.charactersAllowedInNickName30:
              "30 حرفًا مسموحًا به في اللقب",
          AppStrings.enterConfirmPassword: "أدخل تأكيد كلمة المرور",
          AppStrings.passwordDidNotMatch: "لم تتطابق مع كلمة المرور",
          AppStrings.enterMinimum8Character: "أدخل الحد الأدنى من 8 أحرف",
          AppStrings.enterCurrentPassword: "أدخل كلمة المرور الحالية",
          AppStrings.enterNewPassword: "أدخل كلمة السر الجديدة",
          AppStrings.enterValidPassword: "أدخل كلمة سر صالحة",
          AppStrings.minimum8CharactersOneNumberRequired:
              "الحد الأدنى 8 أحرف ، مطلوب رقم واحد",
          AppStrings.minimum8CharactersRequired: "الحد الأدنى المطلوب 8 أحرف",
          AppStrings.maximum25CharactersAllowed:
              "الحد الأقصى المسموح به 25 حرفًا",
          AppStrings.frequency: "تكرار",
          AppStrings.setTimeAndDose: "اضبط الوقت والجرعة",
          AppStrings.howManyTimes: "كم مرة",
          AppStrings.tapToSetEndDate: "اضغط لتعيين تاريخ الانتهاء",
          AppStrings.endDateOptional: "تاريخ الانتهاء (اختياري)",
          AppStrings.startDate: " تاريخ البدء",
          AppStrings.addMedicine: "أضف الدواء",
          AppStrings.addSymptoms: "أضف الأعراض",
          AppStrings.addDose: "أضف جرعه",
          AppStrings.cancel: "إلغاء",
          AppStrings.chooseImage: "اختر صورة",
          AppStrings.takePhoto: "تصوير",
          AppStrings.addMedicinesPhoto: "أضف صور الأدوية",
          AppStrings.done: "تم",
          AppStrings.take: "خذ",
          AppStrings.pills: "حبة",
          AppStrings.howMuchManyDidYouTakeToJustDose:
              "عدد الحبات في الجرعة",
          AppStrings.sound: "صوت",
          AppStrings.setTheSoundOfNotification : "ضبط صوت الإخطارات",
          AppStrings.vibration : "الاهتزاز",
          AppStrings.unitInStock : "وحدة في المخزون",
          AppStrings.pillsInStock : "حبوب في المخزون",
          AppStrings.refillReminder : "تذكير بإعادة التعبئة",
          AppStrings.reminderAndCaregivers : "تذكير ومقدمي الرعاية",
          AppStrings.termsConditionsH1:
              "يتمتع تطبيق فويثي Voithy بمميزات تجعله الأفضل",
          AppStrings.termsConditionsBody1:
              "مع فويثي Voithy، ستحصل على التنبيهات مصممة خصيصا لك لتستطيع إدارة أمورك الصحية والعلاجية بسهوله. ولتظل على تواصل بدائرة الرعاية الخاصة بك من خلال ارسال تنبيهات ومتابعات لعلاجاتك و حالتك الصحية",
          AppStrings.termsConditionsH2: "سهل الاستخدام",
          AppStrings.termsConditionsBody2:
              "تابع علاجاتك وادويتك بمساعدة تطبيقنا المصمم لسهولة الاستخدام.",
          AppStrings.termsConditionsH3: "تنبيهات الجرعات  و و قرب نفاذ مخزون الادوية",
          AppStrings.termsConditionsBody3:
              "سنقوم بتنبيهك قبل ان ينفذ مخزون الدواء",
          AppStrings.passwordsDontMatch: "تأكيد كلمة المرور غير مطابق لكلمة المرور",
          AppStrings.apiError: "حدث خطأ ما: الرسالة",
          AppStrings.wrongOTP: "(OTP) خاطئ. الرجاء ادخال (OTP) صحيح",
          AppStrings.verifyResetPassword: "اضغط للتأكيد وتغيير كلمة المرور",
          AppStrings.somethingWentWrong: "حدث خطأ ما: برجاء المحاولة فيما بعد",
          AppStrings.takePhotoOrChoose: "التقط صورة او\nاختر من الصور المخزنة",
          AppStrings.medicineName: "اسم الدواء",
          AppStrings.strength: "التركيز",
          AppStrings.unit: "الوحدة (ج، ملي جرام، ملي ليتر)",
          AppStrings.condition: "الحالة",
          AppStrings.instructions: "تعليمات",
          AppStrings.next: "التالي",
          AppStrings.back: "السابق",
          AppStrings.day: "يوم",
          AppStrings.week: "اسبوع",
          AppStrings.month: "شهر",
          AppStrings.today: "اليوم, ",
          AppStrings.ml:"م ل",
          AppStrings.mg:"م ج",
          AppStrings.g:"ج",
          AppStrings.everyDay:"كل يوم",
          AppStrings.everyMonth:"كل شهر",
          AppStrings.theDay:"اليوم",
          AppStrings.theMonth:"الشهر",
          AppStrings.oneTime:"مرة",
          AppStrings.twoTime:"مرتان",
          AppStrings.threeTime:"ثلات مرات",
          AppStrings.fourTime:"اربع مرات",
          AppStrings.selection:"اختر",
          AppStrings.dayOrMonth:"اليوم او الشهر",
          AppStrings.pleaseAgreeTermsAndConditions: "من فضلك وافق علي الشروط و الاحكام.",
          AppStrings.comingSoon: "قريبا.",
          AppStrings.saveChanges: "حفظ التغييرات",
          AppStrings.search: "بحث",
          AppStrings.filter: "منقي",
          AppStrings.pillsLeft: "حبوب متبقيه",
          AppStrings.specificDays: "ايام محددة",
          AppStrings.daysInterval:"فترة (ايام)",
          AppStrings.saturday: "السبت",
          AppStrings.sunday: "الاحد",
          AppStrings.monday: "الاثنين",
          AppStrings.tuesday: "الثلاثاء",
          AppStrings.wednesday: "الاربعاء",
          AppStrings.thursday: "الخميس",
          AppStrings.friday: "الجمعة",
          AppStrings.selectFrequency: "اختار التكرار",
          AppStrings.asNeeded: "عند الاحتياج",
          AppStrings.scheduledFor: " المقرر في",
          AppStrings.endDateBeforeStartDate: "تاريخ الانتهاء لايمكن ان يكون قبل تاريخ البدء.",
          AppStrings.startDateInvalid: "تاريخ البدء لا يمكن ان يكون قبل تاريخ اليوم.",
          AppStrings.stock : "مخزون",
          AppStrings.whichDays: "اختر الايام",
          AppStrings.home: "الرئيسية",
          AppStrings.report: "تقرير",
          AppStrings.add: "إضافة",
          AppStrings.myCircle: "دائرتي",
          AppStrings.more: "المزيد",
          AppStrings.everyHowManyDays: "كل كم يوم؟",
          AppStrings.from: "من:",
          AppStrings.to: "إلى:",
          AppStrings.reminder: "المتبقي",
          AppStrings.reminderTime: "وقت التذكرة",
          AppStrings.setTime: "اختر الوقت",
          AppStrings.schedule: "الجدول الزمني",
          AppStrings.name: "الاسم",
          AppStrings.notificationSetup: "ضبط الاشعارات",
          AppStrings.soundType: "نوع الرنين",
          AppStrings.active: "مفعل",
          AppStrings.inactive: "غير مفعل",
          AppStrings.example5:"عدد الحبات مثال: 5",
          AppStrings.intakeDetails: "تفاصيل الجرعة",
          AppStrings.selectTheType : 'حدد النوع',
          AppStrings.type : 'النوع',
          AppStrings.recordingAudio : 'تسجيل الصوت',
          AppStrings.symptomDescription : 'وصف الأعراض',
          AppStrings.mild: 'خفيف',
          AppStrings.moderate : 'معتدل',
          AppStrings.severe : 'شديدة',
          AppStrings.takePhotoOrChooseImage  : 'التقط صورة أو اختر صورة',
          AppStrings.selectSeverity : 'حدد الخطورة',
          AppStrings.date: "التاريخ",
          AppStrings.time: "الوقت",
          AppStrings.addSymptom: "اضف العرض",
          AppStrings.medicationList: "قائمة الأدوية",
          AppStrings.resetFilters: "إعادة الترشيحات",
          AppStrings.apply  : "تطبيق" ,
          AppStrings.symptom  : "عرض",
          AppStrings.severity  : "خطورة",
          AppStrings.toDate  : "ل تاريخ",
          AppStrings.showAllSymptoms : "عرض جميع الأعراض",
          AppStrings.mildSeverity : "الشدة معتدلة",
          AppStrings.moderateSeverity : "الشدة معتدلة",
          AppStrings.severeSeverity  : "الشدة شديدة",
          AppStrings.includePicture : "تشمل الصورة",
          AppStrings.includeAudio : "تشمل الصوت",

          AppStrings.playAudio: "تشغيل الصوت",
          //TODO translate 2
          AppStrings.otpSentSuccessfully: "تم إرسال رمز التحقق بنجاح",
          AppStrings.noMed: "لا توجد أدوية او اعراض مسجلة لليوم",
          AppStrings.startYourJourney: "ابدأ التسجيل",
          AppStrings.suspend : "تعليق",
          AppStrings.outOfStock   : "إنتهى من المخزن",

          AppStrings.symptomsList  : "قائمة الأعراض",
          AppStrings.available  : "متوفرة"
        },
        'en': {
          AppStrings.greeting: 'Welcome',
          AppStrings.trackMedication: 'Track your medication and symptoms',
          AppStrings.helloAndWelcomeHere: 'Hello and \n welcome here!',
          AppStrings.letsStart: "Let's Start",
          AppStrings.chooseYourLanguage: 'Choose Your Language',
          AppStrings.pleaseEnterYourEmailAddress:
              'Please enter your email address',
          AppStrings.pleaseEnterYourPassword: 'Please enter your Password',
          AppStrings.dontHaveAccount: 'Don’t have an account? ',
          AppStrings.forgotYourPassword: 'Forgot your Password?',
          AppStrings.connectWithFacebook: ' Connect with Facebook',
          AppStrings.connectWithGoogle: ' Connect with Google',
          AppStrings.enterYourEmailCorrectly: 'Enter Your Email Correctly',
          AppStrings.enterYourEmailAddress:
              'Enter your email address and we\'ll send you a link to reset your password.',
          AppStrings.resetPassword: 'Reset password',
          AppStrings.changePassword: 'Change password',
          AppStrings.newPassword: 'New password',
          AppStrings.confirmNewPassword: 'Confirm new password',
          AppStrings.pleaseFillTheFieldsCorrectly:
              'Please fill in the required fields correctly ',
          AppStrings.orContinueWith: 'Or continue with',
          AppStrings.getAnOverView:
              'Get an overview of your treatment progress and get motivated to adhere',
          AppStrings.trackYourMedicationAndSymptoms:
              'Track your medication and symptoms ',
          AppStrings.letUsHelpYou:
              'Let us help you manage your complex medication schedules and stock  levels ',
          AppStrings.alreadyAMember: 'Already a member? ',
          AppStrings.neverMissADoseAgain: 'Never miss a dose again',
          AppStrings.getAnOverviewOfYourTreatment:
              'Get an overview of your treatment progress and get motivated to adhere and achieve more',
          AppStrings.inviteAndManageYourCareCircle:
              'Invite and manage your care circle',
          AppStrings.inviteDependentsAndCaregivers:
              'Invite dependents and caregivers to support each other in your treatment plan',
          AppStrings.signUpHeader: 'Create a Voithy account',
          AppStrings.required: "Required",
          AppStrings.firstName: "First name",
          AppStrings.lastName: "Last name",
          AppStrings.mobileNumber: "Mobile number",
          AppStrings.email: "Email",
          AppStrings.password: "Password",
          AppStrings.confirmPassword: "Confirm password",
          AppStrings.signUp: "Sign up",
          AppStrings.signIn: 'Sign In',
          AppStrings.arabic: "عربي",
          AppStrings.english: "English",
          AppStrings.createAccount: "Create a Voithy account",
          AppStrings.termsConditions: "Terms and conditions",
          AppStrings.termsConditionsH1:
              "Voithy’s medication reminder app is number one for a reason.",
          AppStrings.termsConditionsBody1:
              "With Voithy’s, you get personalized reminders for each of your medications and vital drug interaction warnings*. Stay connected to your caregivers through real-time missed medication alerts.",
          AppStrings.termsConditionsH2: "Easy to Use",
          AppStrings.termsConditionsBody2:
              "Manage your medications with our user-friendly app. Get reminders on time, every time.",
          AppStrings.termsConditionsH3: "Med and Refill Reminders",
          AppStrings.termsConditionsBody3:
              "Be notified when your prescriptions are running low so you are never without your meds.",
          AppStrings.verifyAccountH: "Verify Voithy’s account",
          AppStrings.verifyAccountBody:
              "You'll receive a 4 digit code to verify  Voithy’s account via email ",
          AppStrings.resendCode: "Resend code in ",
          AppStrings.verifyCreateAccount: "Verify and create account",
          AppStrings.didnotReceiveCode: "Didn't receive code?",
          AppStrings.requestAgain: " Request again",
          AppStrings.pleaseEnterFirstName: "Please enter your first name",
          AppStrings.pleaseEnterLastName: "Please enter your last name",
          AppStrings.pleaseEnterPassword: "Please enter your password",
          AppStrings.noMed: "No meds or symptoms on this day!",
          AppStrings.startYourJourney: "Start your journey",
          AppStrings.home: "Home",
          AppStrings.playAudio: "Play Audio",
          AppStrings.report: "Report",
          AppStrings.add: "Add",
          AppStrings.myCircle: "My Circle",
          AppStrings.more: "More",
          AppStrings.seeLess: "See Less",
          AppStrings.seeMore: "seeMore",
          AppStrings.getAnOverviewOfYourTreatmentProgress:
              "Get an overview of your treatment progress and get motivated to adhere",
          AppStrings.helloAndWelcomeToVoithy: "Hello and welcome to Voithy!",
          AppStrings.enterMobileNumber: "Enter mobile number",
          AppStrings.enterYourEmail: "Enter your email",
          AppStrings.enterYourPassword: "Enter your password",
          AppStrings.number: "Number",
          AppStrings.nickname: "Nickname",
          AppStrings.myWifeHusbandEtc: "My wife, Husband... etc.",
          AppStrings.createAVoithyAccount: "Create a Voithy account",
          AppStrings.iAgreeWithThe: "I agree with the ",
          AppStrings.country: "Country",
          AppStrings.enterYourEmailAddressAndWellSendYou:
              "Enter your email address and we'll send you a link to reset your password.",
          AppStrings.youllReceiveA4DigitCodeToVerifyVoithysAccountViaEmail:
              "You'll receive a 4 digit code to verify Voithy's account via email",
          AppStrings.createAVoithyAccountForADependent:
              "Create a Voithy account for a dependent",
          AppStrings.toJoinVoithyToGetStartedJustCreateA:
              "to join Voithy to get started, Just create a",
          AppStrings.knowMore: "Know more",
          AppStrings.below: "below.",
          AppStrings.profile: "Profile",
          AppStrings.fullName: "full name",
          AppStrings.phone: "Phone",
          AppStrings.signUpAsdependent: "Sign up as dependent",
          AppStrings.welcomeToVoithy: "Welcome to Voithy",
          AppStrings.yourAccountHasBeenCreatedSuccessfully:
              "your account has been created successfully",
          AppStrings.Cares: "Cares",
          AppStrings.enterFirstName: "Enter first name",
          AppStrings.enterLastName: "Enter last name",
          AppStrings.enterNickname: "Enter nickname",
          AppStrings.enterEmail: "Enter email",
          AppStrings.minimum7Number: "Minimum 7 number",
          AppStrings.maximum13Number: "Minimum 13 number",
          AppStrings.enterPassword: "Enter Password",
          AppStrings.enterOnlyNumbers: "Enter only numbers",
          AppStrings.enterOnlyTextInFirstName: "Enter only text in firstName",
          AppStrings.enterOnlyTextInLastName: "Enter only text in last name",
          AppStrings.enterOnlyTextInNickname: "Enter only text in nickname",
          AppStrings.charactersAllowedInFirstName30:
              "30 characters allowed in first name",
          AppStrings.charactersAllowedInLastName30:
              "30 characters allowed in last name",
          AppStrings.charactersAllowedInNickName30:
              "30 characters allowed in nickname",
          AppStrings.enterConfirmPassword: "Enter confirm password",
          AppStrings.passwordDidNotMatch: "Password did not match",
          AppStrings.enterMinimum8Character: "Enter minimum 8 character",
          AppStrings.enterCurrentPassword: "Enter current password",
          AppStrings.enterNewPassword: "Enter new password",
          AppStrings.enterValidPassword: "Enter valid password",
          AppStrings.minimum8CharactersOneNumberRequired:
              "Minimum 8 characters, One Number required",
          AppStrings.minimum8CharactersRequired:
              "Minimum 8 characters required",
          AppStrings.maximum25CharactersAllowed:
              "Maximum 25 characters allowed",
          AppStrings.passwordsDontMatch: "Passwords don't match each other.",
          AppStrings.apiError: "Something went wrong. Message: ",
          AppStrings.wrongOTP: "Wrong OTP. Please enter valid otp code.",
          AppStrings.verifyResetPassword: "Verify and change password",
          AppStrings.addMedicine: "Add medicine",
          AppStrings.takePhotoOrChoose: "Take photo or\nchoose from gallery",
          AppStrings.medicineName: "Medicine name",
          AppStrings.strength: "Strength",
          AppStrings.unit: "Unit (g, mg, ml )",
          AppStrings.condition: "Condition",
          AppStrings.instructions: "Instructions",
          AppStrings.next: "Next",
          AppStrings.back: "Back",
          AppStrings.day: "Day",
          AppStrings.week: "Week",
          AppStrings.month: "Month",
          AppStrings.frequency: "Frequency",
          AppStrings.setTimeAndDose: "Set time and dose",
          AppStrings.howManyTimes: "How many times",
          AppStrings.tapToSetEndDate: "Tap to set end date",
          AppStrings.endDateOptional: "End date (Optional)",
          AppStrings.startDate: "Start Date",
          AppStrings.otpSentSuccessfully: "OTP sent successfully",
          AppStrings.saveChanges: "Save Changes",
          AppStrings.addSymptoms: "Add Symptoms",
          AppStrings.addDose: "Add Dose",
          AppStrings.cancel: "Cancel",
          AppStrings.chooseImage: "Choose Image",
          AppStrings.takePhoto: "Take Photo",
          AppStrings.done: "Done",
          AppStrings.addMedicinesPhoto: "Add medicines photo",
          AppStrings.howMuchManyDidYouTakeToJustDose:
              "How many units per dose?",
          AppStrings.take: "Take",
          AppStrings.pills: "pills",
          AppStrings.somethingWentWrong: "Something went wrong, please try again later.",
          AppStrings.sound: "Sound",
          AppStrings.setTheSoundOfNotification : "Set the sound of notification",
          AppStrings.vibration : "Vibration",
          AppStrings.unitInStock : "Units in stock",
          AppStrings.pillsInStock : "Pills in stock",
          AppStrings.refillReminder : "Refill reminder",
          AppStrings.reminderAndCaregivers : "Reminder and caregivers",
          AppStrings.today: "Today, ",
          AppStrings.toDate: "to date",
          AppStrings.providePermission: "You need to provide permission",
          AppStrings.ml:"ml",
          AppStrings.mg:"mg",
          AppStrings.g:"g",
          AppStrings.everyDay:"Every Day",
          AppStrings.everyMonth:"Every Month",
          AppStrings.oneTime:"1 time",
          AppStrings.twoTime:"2 times",
          AppStrings.threeTime:"3 times",
          AppStrings.fourTime:"4 times",
          AppStrings.selection:"Select",
          AppStrings.theDay:"day",
          AppStrings.theMonth:"month",
          AppStrings.dayOrMonth:"day or month",
          AppStrings.pleaseAgreeTermsAndConditions: "Please Agree Terms And Conditions.",
          AppStrings.comingSoon: "Coming soon.",
          AppStrings.selectFrequency: "Choose the frequency",
          AppStrings.specificDays: "Specific days",
          AppStrings.asNeeded: "As needed",
          AppStrings.daysInterval:"Days interval",
          AppStrings.whichDays: "Which days",
          AppStrings.search: "Search",
          AppStrings.filter: "Filter",
          AppStrings.pillsLeft: "Pills left",
          AppStrings.saturday: "Saturday",
          AppStrings.sunday: "Sunday",
          AppStrings.monday: "Monday",
          AppStrings.tuesday: "Tuesday",
          AppStrings.wednesday: "Wednesday",
          AppStrings.thursday: "Thursday",
          AppStrings.friday: "Friday",
          AppStrings.scheduledFor: "Scheduled for : ",
          AppStrings.endDateBeforeStartDate: "End date can't be before start date.",
          AppStrings.startDateInvalid: "Start date can't be before today date.",
          AppStrings.stock : "Stock",
          AppStrings.everyHowManyDays: "Every how many days?",
          AppStrings.reminder: "Reminder",
          AppStrings.reminderTime: "Reminder Time",
          AppStrings.setTime: "Set time",
          AppStrings.schedule: "Schedule",
          AppStrings.name: "Name",
          AppStrings.dateRange: "Date Range",
          AppStrings.from: "From: ",
          AppStrings.to: "To: ",
          AppStrings.notificationSetup: "Notification setup",
          AppStrings.soundType: "Sound type",
          AppStrings.active: "Active",
          AppStrings.inactive: "Inactive",
          AppStrings.example5:"number of pills ex: 5",
          AppStrings.intakeDetails: "Intake details",
          AppStrings.selectTheType : 'Select the type',
          AppStrings.type : 'Type',
          AppStrings.recordingAudio : 'Recording audio',
          AppStrings.symptomDescription : 'Symptom description',
          AppStrings.mild: 'Mild',
          AppStrings.moderate : 'Moderate',
          AppStrings.severe : 'Severe',
          AppStrings.takePhotoOrChooseImage  : 'Take photo or choose image',
          AppStrings.selectSeverity : 'Select severity',
          AppStrings.date: "Date",
          AppStrings.time: "Time",
          AppStrings.medicationList: "Medication List",
          AppStrings.addSymptom: "Add symptom",
          AppStrings.resetFilters: "Reset filters",
          AppStrings.termsConditions : "termsConditions",
          AppStrings.suspend : "Suspend",
          AppStrings.outOfStock   : "Out of Stock",
          AppStrings.available  : "Available",
          AppStrings.apply  : "Apply",
          AppStrings.symptomsList  : "Symptoms List",
          AppStrings.symptom  : "Symptom",
          AppStrings.severity  : "Severity",
          AppStrings.showAllSymptoms : "showAllSymptoms",
          AppStrings.mildSeverity : "mildSeverity",
          AppStrings.moderateSeverity : "moderateSeverity",
          AppStrings.severeSeverity  : "severeSeverity",
          AppStrings.includePicture : "includePicture",
          AppStrings.includeAudio : "includeAudio",
                }
      };
}
